### ISSUE TITLE
Example

### ISSUE THREAD

**Issue by Hantoo** [CarlosFdez/pyNDI#1]
Hi,
Have you an example of code that is working?
I tried to get it working myself but the finder isn't working properly - not showing an sources.

**Comment by CarlosFdez** [comment]
I'll try to send something tomorrow. To be honest though, I wouldn't be surprised if it stopped working due to some NDI update

**Comment by Hantoo** [comment]
Got it to work!
I'll fork off, make an example and then add a pull request :) 

Edit: Pull Request Added
